# Generated by Django 5.2.3 on 2025-08-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('slug', models.TextField(max_length=150)),
                ('timeDate', models.DateField(blank=True)),
            ],
        ),
    ]
