# Generated by Django 5.2.3 on 2025-08-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=14)),
                ('content', models.TextField()),
                ('TimeDate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
